apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-challenge-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-challenge
  template:
    metadata:
      labels:
        app: backend-challenge
    spec:
      containers:
        - name: backend-challenge
          image: cleberfatec/backend-challenge:1.0
          ports:
            - containerPort: 8080
