apiVersion: v1
kind: Service
metadata:
  name: backend-challenge-service
spec:
  selector:
    app: backend-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
